name: SimpleNick
main: com.dark.simplenick.SimpleNick
version: 1.2
description: A simple plugin to set nicknames.
api-version: 1.16

commands:
  nick:
    description: Changes your nickname
    usage: /nick <nickname> or /nick reset
