name: SimpleNick
main: com.example.simplenick.SimpleNick
version: 1.0
commands:
  nick:
    description: Changes your nickname.
    usage: /nick <nickname> | /nick reset
permissions:
  simplenick.use:
    description: Allows players to change their nickname
    default: true
