name: NickPlugin
main: com.example.nickplugin.NickPlugin
version: 1.1
api-version: 1.13
commands:
  nick:
    description: Change your nickname or reset it.
    usage: /nick <newNickname> or /nick reset
    permission: nickplugin.use
