name: SimpleNick
main: com.dark.simplenick.SimpleNick
version: 1.2
commands:
  nick:
    description: Change your nickname or reset it.
  nickreload:
    description: Reloads the SimpleNick configuration.
    permission: simplenick.reload
permissions:
  simplenick.use:
    description: Allows a player to use /nick.
    default: true
  simplenick.others:
    description: Allows a player to change other players' nicknames.
    default: op
  simplenick.reload:
    description: Allows a player to reload the SimpleNick configuration.
    default: op
